# Generated by Django 5.0.1 on 2025-11-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hint_level",
            field=models.IntegerField(
                choices=[
                    (3, "레벨 3 (실력자 - 소크라테스식)"),
                    (2, "레벨 2 (보통 - 개념 힌트)"),
                    (1, "레벨 1 (기초 - 구체적 힌트)"),
                ],
                default=2,
                help_text="1: 구체적 힌트, 2: 개념 힌트, 3: 소크라테스식",
                verbose_name="힌트 레벨",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skill_mode",
            field=models.CharField(
                choices=[("auto", "자동"), ("manual", "수동")],
                default="auto",
                help_text="auto: 문제 풀이 기록으로 자동 갱신, manual: 관리자가 수동 설정",
                max_length=10,
                verbose_name="실력 지표 모드",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skill_score",
            field=models.FloatField(
                default=50.0,
                help_text="0~100 사이의 점수. 높을수록 초보, 낮을수록 실력자",
                verbose_name="실력 점수",
            ),
        ),
    ]
