# Generated by Django 5.0.1 on 2025-11-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_user_birth_date_user_gender_user_name_user_nickname_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("code", models.CharField(max_length=6, verbose_name="인증 코드")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료일")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증 완료 여부"),
                ),
            ],
            options={
                "verbose_name": "이메일 인증 코드",
                "verbose_name_plural": "이메일 인증 코드 목록",
                "db_table": "email_verification_codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
