# Generated by Django 5.0.1 on 2025-11-04 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_id",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="문제 ID"
                    ),
                ),
                (
                    "step_title",
                    models.CharField(blank=True, max_length=200, verbose_name="단계 제목"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "레벨 1"),
                            (2, "레벨 2"),
                            (3, "레벨 3"),
                            (4, "레벨 4"),
                            (5, "레벨 5"),
                        ],
                        verbose_name="난이도",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                ("description", models.TextField(verbose_name="문제 설명")),
                ("input_description", models.TextField(verbose_name="입력 설명")),
                ("output_description", models.TextField(verbose_name="출력 설명")),
                ("examples", models.JSONField(default=list, verbose_name="예시")),
                ("url", models.URLField(blank=True, verbose_name="문제 URL")),
                ("solutions", models.JSONField(default=list, verbose_name="정답 코드")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제 목록",
                "db_table": "problems",
                "ordering": ["problem_id"],
            },
        ),
        migrations.CreateModel(
            name="HintRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hint_level",
                    models.CharField(
                        choices=[
                            ("small", "소 힌트"),
                            ("medium", "중 힌트"),
                            ("large", "대 힌트"),
                        ],
                        max_length=20,
                        verbose_name="힌트 레벨",
                    ),
                ),
                ("user_code", models.TextField(verbose_name="사용자 코드")),
                ("hint_response", models.TextField(verbose_name="힌트 응답")),
                (
                    "model_used",
                    models.CharField(blank=True, max_length=100, verbose_name="사용 모델"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_requests",
                        to="coding_test.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "힌트 요청",
                "verbose_name_plural": "힌트 요청 목록",
                "db_table": "hint_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(verbose_name="제출 코드")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("success", "성공"),
                            ("fail", "실패"),
                            ("error", "에러"),
                        ],
                        max_length=20,
                        verbose_name="결과",
                    ),
                ),
                ("output", models.TextField(blank=True, verbose_name="출력")),
                ("error_message", models.TextField(blank=True, verbose_name="에러 메시지")),
                (
                    "execution_count",
                    models.IntegerField(default=1, verbose_name="실행 횟수"),
                ),
                ("time_spent", models.IntegerField(default=0, verbose_name="소요 시간(초)")),
                ("rating_earned", models.IntegerField(default=0, verbose_name="획득 점수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="coding_test.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "제출 기록",
                "verbose_name_plural": "제출 기록 목록",
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="북마크일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="coding_test.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 북마크",
                "verbose_name_plural": "문제 북마크 목록",
                "db_table": "problem_bookmarks",
                "ordering": ["-created_at"],
                "unique_together": {("user", "problem")},
            },
        ),
    ]
