# Generated by Django 5.0.1 on 2025-11-05 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_id",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="문제 ID"
                    ),
                ),
                ("input_data", models.TextField(verbose_name="입력 데이터")),
                ("expected_output", models.TextField(verbose_name="예상 출력")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="이 테스트 케이스가 필요한 이유", verbose_name="설명"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 대기"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="검토 의견")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제안일"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="검토일"),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_case_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제안자",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_test_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
            ],
            options={
                "verbose_name": "테스트 케이스 제안",
                "verbose_name_plural": "테스트 케이스 제안 목록",
                "db_table": "test_case_proposals",
                "ordering": ["-created_at"],
            },
        ),
    ]
