# Generated by Django 5.0.1 on 2025-11-05 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0002_testcaseproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_id",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="문제 ID"
                    ),
                ),
                ("solution_code", models.TextField(verbose_name="솔루션 코드")),
                (
                    "language",
                    models.CharField(
                        default="python", max_length=50, verbose_name="프로그래밍 언어"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="이 솔루션에 대한 설명", verbose_name="설명"
                    ),
                ),
                (
                    "is_reference",
                    models.BooleanField(
                        default=True,
                        help_text="JSON에 추가할지 여부",
                        verbose_name="참조 솔루션 여부",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 대기"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="검토 의견")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제안일"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="검토일"),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제안자",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_solutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
            ],
            options={
                "verbose_name": "솔루션 제안",
                "verbose_name_plural": "솔루션 제안 목록",
                "db_table": "solution_proposals",
                "ordering": ["-created_at"],
            },
        ),
    ]
