# Generated by Django 5.0.1 on 2025-11-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0003_solutionproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("api", "API 방식 (Hugging Face)"),
                            ("local", "로컬 로드 방식"),
                        ],
                        default="api",
                        max_length=20,
                        verbose_name="모델 사용 방식",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API 방식 사용 시 필요",
                        max_length=200,
                        verbose_name="Hugging Face API Key",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="Qwen/Qwen2.5-Coder-32B-Instruct",
                        max_length=200,
                        verbose_name="모델 이름",
                    ),
                ),
                (
                    "is_model_loaded",
                    models.BooleanField(
                        default=False,
                        help_text="로컬 모드에서 모델이 메모리에 로드되었는지 여부",
                        verbose_name="모델 로드 여부",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 수정일"),
                ),
            ],
            options={
                "verbose_name": "AI 모델 설정",
                "verbose_name_plural": "AI 모델 설정",
                "db_table": "ai_model_config",
            },
        ),
        migrations.CreateModel(
            name="ProblemProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_id",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="문제 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문제 제목")),
                (
                    "step_title",
                    models.CharField(blank=True, max_length=200, verbose_name="단계 제목"),
                ),
                ("description", models.TextField(verbose_name="문제 설명")),
                ("input_description", models.TextField(verbose_name="입력 설명")),
                ("output_description", models.TextField(verbose_name="출력 설명")),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "레벨 1"),
                            (2, "레벨 2"),
                            (3, "레벨 3"),
                            (4, "레벨 4"),
                            (5, "레벨 5"),
                            (6, "레벨 6"),
                            (7, "레벨 7"),
                            (8, "레벨 8"),
                            (9, "레벨 9"),
                            (10, "레벨 10"),
                            (11, "레벨 11"),
                            (12, "레벨 12"),
                            (13, "레벨 13"),
                            (14, "레벨 14"),
                            (15, "레벨 15"),
                        ],
                        verbose_name="난이도",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                ("solution_code", models.TextField(verbose_name="참조 솔루션 코드")),
                (
                    "language",
                    models.CharField(
                        default="python", max_length=50, verbose_name="프로그래밍 언어"
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        default=list,
                        help_text="입력/출력 테스트 케이스 목록",
                        verbose_name="테스트 케이스",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 대기"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="검토 의견")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제안일"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="검토일"),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제안자",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_problems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 제안",
                "verbose_name_plural": "문제 제안 목록",
                "db_table": "problem_proposals",
                "ordering": ["-created_at"],
            },
        ),
    ]
