# Generated by Django 5.0.1 on 2025-11-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0004_aimodelconfig_problemproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="model_name",
            field=models.CharField(
                choices=[
                    (
                        "Qwen/Qwen2.5-Coder-32B-Instruct",
                        "Qwen 2.5 Coder 32B (유료 API 필요)",
                    ),
                    ("Qwen/Qwen2.5-Coder-7B-Instruct", "Qwen 2.5 Coder 7B (무료 API 가능)"),
                ],
                default="Qwen/Qwen2.5-Coder-7B-Instruct",
                max_length=200,
                verbose_name="모델 이름",
            ),
        ),
    ]
