# Generated by Django 5.0.1 on 2025-11-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0005_alter_aimodelconfig_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="model_name",
            field=models.CharField(
                choices=[
                    (
                        "Qwen/Qwen2.5-Coder-32B-Instruct",
                        "Qwen 2.5 Coder 32B (API 키 필요)",
                    ),
                    ("Qwen/Qwen2.5-Coder-7B-Instruct", "Qwen 2.5 Coder 7B (API 키 필요)"),
                    (
                        "Qwen/Qwen2.5-Coder-1.5B-Instruct",
                        "Qwen 2.5 Coder 1.5B (로컬 실행 권장)",
                    ),
                    (
                        "Qwen/Qwen2.5-Coder-0.5B-Instruct",
                        "Qwen 2.5 Coder 0.5B (로컬 실행 권장)",
                    ),
                ],
                default="Qwen/Qwen2.5-Coder-7B-Instruct",
                max_length=200,
                verbose_name="모델 이름",
            ),
        ),
    ]
