# Generated by Django 5.0.1 on 2025-11-06 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0006_alter_aimodelconfig_model_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작 시간"),
                ),
                (
                    "first_hint_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="첫 힌트 요청 시간"
                    ),
                ),
                (
                    "first_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="첫 실행 시간"),
                ),
                (
                    "solved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="해결 시간"),
                ),
                ("hint_count", models.IntegerField(default=0, verbose_name="힌트 요청 횟수")),
                ("run_count", models.IntegerField(default=0, verbose_name="실행 횟수")),
                (
                    "max_code_length",
                    models.IntegerField(default=0, verbose_name="최대 코드 길이"),
                ),
                ("is_solved", models.BooleanField(default=False, verbose_name="해결 여부")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="coding_test.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 풀이 세션",
                "verbose_name_plural": "문제 풀이 세션 목록",
                "db_table": "problem_sessions",
                "ordering": ["-started_at"],
                "unique_together": {("user", "problem")},
            },
        ),
    ]
