# Generated by Django 5.0.1 on 2025-11-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0007_problemsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="model_name",
            field=models.CharField(
                choices=[
                    (
                        "meta-llama/Llama-3.2-3B-Instruct",
                        "Llama 3.2 3B Instruct (API 모드 지원)",
                    ),
                    (
                        "Qwen/Qwen2.5-Coder-32B-Instruct",
                        "Qwen 2.5 Coder 32B (API 모드 지원)",
                    ),
                    (
                        "mistralai/Mistral-7B-Instruct-v0.3",
                        "Mistral 7B Instruct (API 모드 지원)",
                    ),
                    ("google/gemma-2-9b-it", "Gemma 2 9B IT (API 모드 지원)"),
                ],
                default="meta-llama/Llama-3.2-3B-Instruct",
                max_length=200,
                verbose_name="모델 이름",
            ),
        ),
    ]
