# Generated by Django 5.0.1 on 2025-11-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0008_update_ai_model_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("first_problem", "첫 문제 해결"),
                            ("problem_streak_7", "7일 연속 문제 풀이"),
                            ("problem_streak_30", "30일 연속 문제 풀이"),
                            ("problems_10", "문제 10개 해결"),
                            ("problems_50", "문제 50개 해결"),
                            ("problems_100", "문제 100개 해결"),
                            ("all_easy", "모든 Easy 문제 해결"),
                            ("speed_master", "스피드 마스터 (빠른 해결)"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="뱃지 유형",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="뱃지 이름")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "icon",
                    models.CharField(default="🏆", max_length=10, verbose_name="아이콘"),
                ),
            ],
            options={
                "verbose_name": "뱃지",
                "verbose_name_plural": "뱃지 목록",
                "db_table": "badges",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("daily_login", "매일 로그인"),
                            ("daily_problem", "매일 문제 풀기"),
                            ("weekly_problems", "주간 문제 목표"),
                            ("monthly_problems", "월간 문제 목표"),
                        ],
                        max_length=50,
                        verbose_name="목표 유형",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="목표 이름")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "target_value",
                    models.IntegerField(help_text="예: 7일, 10문제", verbose_name="목표 값"),
                ),
            ],
            options={
                "verbose_name": "목표",
                "verbose_name_plural": "목표 목록",
                "db_table": "goals",
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_problems",
                    models.JSONField(
                        default=list,
                        help_text="설문조사 기반으로 생성된 문제 ID 리스트",
                        verbose_name="추천 문제 목록",
                    ),
                ),
                ("current_step", models.IntegerField(default=0, verbose_name="현재 단계")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "로드맵",
                "verbose_name_plural": "로드맵 목록",
                "db_table": "roadmaps",
            },
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.IntegerField(default=0, verbose_name="현재 값")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_goals",
                        to="coding_test.goal",
                        verbose_name="목표",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 목표",
                "verbose_name_plural": "사용자 목표 목록",
                "db_table": "user_goals",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programming_experience",
                    models.CharField(
                        choices=[
                            ("beginner", "초급 (0-1년)"),
                            ("intermediate", "중급 (1-3년)"),
                            ("advanced", "고급 (3년 이상)"),
                        ],
                        max_length=20,
                        verbose_name="프로그래밍 경험",
                    ),
                ),
                (
                    "learning_goals",
                    models.JSONField(
                        default=list,
                        help_text='선택한 학습 목표 리스트 (예: ["알고리즘", "자료구조", "코딩테스트"])',
                        verbose_name="학습 목표",
                    ),
                ),
                (
                    "interested_topics",
                    models.JSONField(
                        default=list,
                        help_text='관심 있는 주제 리스트 (예: ["배열", "문자열", "DP"])',
                        verbose_name="관심 분야",
                    ),
                ),
                (
                    "preferred_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "쉬움 (Level 1-5)"),
                            ("medium", "중간 (Level 6-10)"),
                            ("hard", "어려움 (Level 11-15)"),
                        ],
                        max_length=20,
                        verbose_name="선호 난이도",
                    ),
                ),
                (
                    "daily_problem_goal",
                    models.IntegerField(
                        default=1,
                        help_text="하루에 풀고 싶은 문제 개수",
                        verbose_name="하루 목표 문제 수",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 설문조사",
                "verbose_name_plural": "사용자 설문조사 목록",
                "db_table": "user_surveys",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="획득일"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="coding_test.badge",
                        verbose_name="뱃지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 뱃지",
                "verbose_name_plural": "사용자 뱃지 목록",
                "db_table": "user_badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
