# Generated by Django 5.0.1 on 2025-11-07 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0009_badge_goal_roadmap_usergoal_usersurvey_userbadge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="model_name",
            field=models.CharField(
                choices=[
                    (
                        "meta-llama/Llama-3.2-3B-Instruct",
                        "Llama 3.2 3B Instruct (API 모드 지원)",
                    ),
                    (
                        "Qwen/Qwen2.5-Coder-32B-Instruct",
                        "Qwen 2.5 Coder 32B (API 모드 지원)",
                    ),
                    (
                        "mistralai/Mistral-7B-Instruct-v0.3",
                        "Mistral 7B Instruct (API 모드 지원)",
                    ),
                    ("google/gemma-2-9b-it", "Gemma 2 9B IT (API 모드 지원)"),
                    (
                        "ModelCloud/Brumby-14B-Base-GPTQMODEL-W4A16-v2",
                        "Brumby 14B Base (API 모드 지원)",
                    ),
                ],
                default="meta-llama/Llama-3.2-3B-Instruct",
                max_length=200,
                verbose_name="모델 이름",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("first_problem", "첫 문제 해결"),
                    ("problem_streak_7", "7일 연속 문제 풀이"),
                    ("problem_streak_30", "30일 연속 문제 풀이"),
                    ("problems_10", "문제 10개 해결"),
                    ("problems_50", "문제 50개 해결"),
                    ("problems_100", "문제 100개 해결"),
                    ("all_easy", "모든 Easy 문제 해결"),
                    ("speed_master", "스피드 마스터 (빠른 해결)"),
                    ("syntax_typo_monster", "타이핑 괴물"),
                    ("syntax_racer", "오타 레이서"),
                    ("syntax_careful", "꼼꼼 감정사"),
                    ("syntax_perfect", "문법 나치"),
                    ("skill_genius", "코딩 천재"),
                    ("skill_master", "알고리즘 마스터"),
                    ("skill_steady", "꾸준러"),
                    ("skill_newbie", "코딩 새싹"),
                    ("logic_action_first", "일단 고"),
                    ("logic_trial_error", "시행착오의 달인"),
                    ("logic_king", "로직 킹"),
                    ("no_hint_10", "독고다이"),
                    ("perfect_coder", "퍼펙트 코더"),
                    ("persistence_king", "집념의 화신"),
                    ("all_rounder", "만능 엔터테이너"),
                    ("attendance_3days", "출석왕"),
                    ("hello_world", "헬로 월드"),
                    ("korean_grammar", "유사 한국인"),
                    ("unbreakable", "불굴의 의지"),
                    ("night_owl", "야행성"),
                    ("hint_collector", "힌트 수집가"),
                    ("button_mania", "버튼 매니아"),
                ],
                max_length=50,
                unique=True,
                verbose_name="뱃지 유형",
            ),
        ),
        migrations.CreateModel(
            name="HintMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_similarity",
                    models.FloatField(
                        default=0,
                        help_text="logic_steps 기반 0-100",
                        verbose_name="코드 유사도 (%)",
                    ),
                ),
                (
                    "syntax_errors",
                    models.IntegerField(default=0, verbose_name="문법 오류 개수"),
                ),
                (
                    "logic_errors",
                    models.IntegerField(default=0, verbose_name="논리 오류 개수"),
                ),
                (
                    "concept_level",
                    models.IntegerField(
                        default=1, help_text="1-5 단계", verbose_name="개념 이해도"
                    ),
                ),
                ("hint_count", models.IntegerField(default=0, verbose_name="힌트 요청 횟수")),
                (
                    "hint_level_used",
                    models.IntegerField(
                        default=3,
                        help_text="1=초급, 2=중급, 3=고급",
                        verbose_name="사용한 힌트 레벨",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_metrics",
                        to="coding_test.problem",
                        verbose_name="문제",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "힌트 지표",
                "verbose_name_plural": "힌트 지표 목록",
                "db_table": "hint_metrics",
                "ordering": ["-created_at"],
            },
        ),
    ]
