# Generated by Django 5.0.1 on 2025-11-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0010_alter_aimodelconfig_model_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadmap",
            options={
                "ordering": ["-is_active", "-created_at"],
                "verbose_name": "로드맵",
                "verbose_name_plural": "로드맵 목록",
            },
        ),
        migrations.AddField(
            model_name="roadmap",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="현재 선택된 로드맵 여부", verbose_name="활성화 상태"
            ),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmaps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
