# Generated by Django 5.0.1 on 2025-11-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0011_alter_roadmap_options_roadmap_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="condition_description",
            field=models.CharField(
                blank=True,
                help_text='사용자에게 표시할 획득 방법 (예: "문제를 10개 풀면 획득")',
                max_length=200,
                verbose_name="획득 조건 설명",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="condition_target",
            field=models.IntegerField(
                default=0, help_text="횟수 조건의 경우 목표 횟수", verbose_name="목표 값"
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("count", "횟수 달성"),
                    ("average", "평균 기준"),
                    ("streak", "연속 달성"),
                    ("first", "최초 달성"),
                    ("special", "특수 조건"),
                ],
                default="special",
                max_length=20,
                verbose_name="조건 유형",
            ),
        ),
    ]
