# Generated by Django 5.0.1 on 2025-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0012_add_badge_condition_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hintmetrics",
            name="code_similarity",
        ),
        migrations.RemoveField(
            model_name="hintmetrics",
            name="concept_level",
        ),
        migrations.RemoveField(
            model_name="hintmetrics",
            name="hint_level_used",
        ),
        migrations.RemoveField(
            model_name="hintmetrics",
            name="logic_errors",
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="algorithm_efficiency",
            field=models.IntegerField(
                default=0, help_text="시간/공간 복잡도 1-5", verbose_name="알고리즘 효율성"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="algorithm_pattern_match",
            field=models.FloatField(
                default=0, help_text="0-100", verbose_name="알고리즘 패턴 일치도 (%)"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="code_complexity",
            field=models.FloatField(
                default=0, help_text="Cyclomatic Complexity", verbose_name="코드 복잡도"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="code_conciseness",
            field=models.IntegerField(
                default=0, help_text="중복 제거, DRY 1-5", verbose_name="코드 간결성"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="code_quality_score",
            field=models.FloatField(
                default=0,
                help_text="Maintainability Index 0-100",
                verbose_name="코드 품질 점수",
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="code_readability",
            field=models.IntegerField(
                default=0, help_text="변수명, 주석 1-5", verbose_name="코드 가독성"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="design_pattern_fit",
            field=models.IntegerField(
                default=0, help_text="알고리즘 패턴 1-5", verbose_name="설계 패턴 적합성"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="edge_case_handling",
            field=models.IntegerField(
                default=0, help_text="경계 조건, 예외 1-5", verbose_name="엣지 케이스 처리"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="function_separation",
            field=models.IntegerField(
                default=0, help_text="모듈화, 단일 책임 1-5", verbose_name="함수 분리도"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="hint_config",
            field=models.JSONField(
                default=dict, help_text="사용자가 선택한 힌트 구성", verbose_name="힌트 구성"
            ),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="pep8_violations",
            field=models.IntegerField(default=0, verbose_name="PEP8 위반 개수"),
        ),
        migrations.AddField(
            model_name="hintmetrics",
            name="test_pass_rate",
            field=models.FloatField(
                default=0, help_text="0-100", verbose_name="테스트 통과율 (%)"
            ),
        ),
    ]
