# Generated by Django 5.0.1 on 2025-11-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0013_remove_hintmetrics_code_similarity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="algorithm_efficiency",
            field=models.IntegerField(default=3, verbose_name="알고리즘 효율성"),
        ),
        migrations.AddField(
            model_name="submission",
            name="code_conciseness",
            field=models.IntegerField(default=3, verbose_name="코드 간결성"),
        ),
        migrations.AddField(
            model_name="submission",
            name="code_quality_score",
            field=models.FloatField(default=0.0, verbose_name="코드 품질 점수"),
        ),
        migrations.AddField(
            model_name="submission",
            name="code_readability",
            field=models.IntegerField(default=3, verbose_name="코드 가독성"),
        ),
        migrations.AddField(
            model_name="submission",
            name="edge_case_handling",
            field=models.IntegerField(default=3, verbose_name="엣지 케이스 처리"),
        ),
        migrations.AddField(
            model_name="submission",
            name="execution_time",
            field=models.FloatField(default=0.0, verbose_name="실행 시간(ms)"),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="정답 여부"),
        ),
        migrations.AddField(
            model_name="submission",
            name="memory_usage",
            field=models.FloatField(default=0.0, verbose_name="메모리 사용량(KB)"),
        ),
        migrations.AddField(
            model_name="submission",
            name="passed_tests",
            field=models.IntegerField(default=0, verbose_name="통과한 테스트 수"),
        ),
        migrations.AddField(
            model_name="submission",
            name="pep8_violations",
            field=models.IntegerField(default=0, verbose_name="PEP8 위반 개수"),
        ),
        migrations.AddField(
            model_name="submission",
            name="security_awareness",
            field=models.IntegerField(default=3, verbose_name="보안 인식"),
        ),
        migrations.AddField(
            model_name="submission",
            name="syntax_errors",
            field=models.IntegerField(default=0, verbose_name="문법 오류 개수"),
        ),
        migrations.AddField(
            model_name="submission",
            name="test_coverage_estimate",
            field=models.IntegerField(default=3, verbose_name="테스트 커버리지 추정"),
        ),
        migrations.AddField(
            model_name="submission",
            name="test_pass_rate",
            field=models.FloatField(default=0.0, verbose_name="테스트 통과율"),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_tests",
            field=models.IntegerField(default=0, verbose_name="전체 테스트 수"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="result",
            field=models.CharField(
                choices=[
                    ("pending", "대기 중"),
                    ("success", "성공"),
                    ("fail", "실패"),
                    ("error", "에러"),
                ],
                default="pending",
                max_length=20,
                verbose_name="결과",
            ),
        ),
        migrations.CreateModel(
            name="ProblemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solved", "내가 푼 문제"),
                            ("upgrade", "업그레이드"),
                            ("upgrading", "업그레이드(푸는 중)"),
                        ],
                        default="upgrade",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("best_score", models.FloatField(default=0.0, verbose_name="최고 점수")),
                (
                    "first_solved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="최초 정답일"),
                ),
                (
                    "last_submitted_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 제출일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="coding_test.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 상태",
                "verbose_name_plural": "문제 상태 목록",
                "db_table": "problem_status",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "problem")},
            },
        ),
    ]
