# Generated by Django 5.0.1 on 2025-11-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0014_submission_algorithm_efficiency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelconfig",
            name="runpod_api_key",
            field=models.CharField(
                blank=True,
                help_text="Runpod API Key (선택사항, vLLM 서버에 인증이 필요한 경우)",
                max_length=200,
                null=True,
                verbose_name="Runpod API Key",
            ),
        ),
        migrations.AddField(
            model_name="aimodelconfig",
            name="runpod_endpoint",
            field=models.URLField(
                blank=True,
                help_text="Runpod vLLM 서버 엔드포인트 (예: https://abc-8000.proxy.runpod.net)",
                max_length=500,
                null=True,
                verbose_name="Runpod Endpoint URL",
            ),
        ),
        migrations.AlterField(
            model_name="aimodelconfig",
            name="mode",
            field=models.CharField(
                choices=[
                    ("api", "API 방식 (Hugging Face)"),
                    ("local", "로컬 로드 방식"),
                    ("runpod", "Runpod vLLM 방식"),
                ],
                default="api",
                max_length=20,
                verbose_name="모델 사용 방식",
            ),
        ),
    ]
