# Generated by Django 5.0.1 on 2025-11-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0015_aimodelconfig_runpod_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemstatus",
            name="star_count",
            field=models.IntegerField(default=0, verbose_name="별점"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "레벨 1"),
                    (2, "레벨 2"),
                    (3, "레벨 3"),
                    (4, "레벨 4"),
                    (5, "레벨 5"),
                    (6, "레벨 6"),
                    (7, "레벨 7"),
                    (8, "레벨 8"),
                    (9, "레벨 9"),
                    (10, "레벨 10"),
                    (11, "레벨 11"),
                    (12, "레벨 12"),
                    (13, "레벨 13"),
                    (14, "레벨 14"),
                    (15, "레벨 15"),
                    (16, "레벨 16"),
                    (17, "레벨 17"),
                    (18, "레벨 18"),
                    (19, "레벨 19"),
                    (20, "레벨 20"),
                    (21, "레벨 21"),
                    (22, "레벨 22"),
                    (23, "레벨 23"),
                    (24, "레벨 24"),
                    (25, "레벨 25"),
                    (26, "레벨 26"),
                ],
                verbose_name="난이도",
            ),
        ),
    ]
