# Generated by Django 5.0.1 on 2025-11-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0016_problemstatus_star_count_alter_problem_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelconfig",
            name="hint_engine",
            field=models.CharField(
                choices=[("api", "기존 API 방식"), ("langgraph", "LangGraph 방식")],
                default="api",
                help_text="힌트 생성 방식 선택 (관리자만 변경 가능)",
                max_length=20,
                verbose_name="힌트 엔진",
            ),
        ),
        migrations.AddField(
            model_name="aimodelconfig",
            name="openai_api_key",
            field=models.CharField(
                blank=True,
                help_text="OpenAI API 방식 사용 시 필요",
                max_length=200,
                verbose_name="OpenAI API Key",
            ),
        ),
        migrations.AddField(
            model_name="hintrequest",
            name="hint_type",
            field=models.CharField(blank=True, max_length=50, verbose_name="힌트 타입"),
        ),
        migrations.AddField(
            model_name="hintrequest",
            name="is_langgraph",
            field=models.BooleanField(default=False, verbose_name="LangGraph 사용 여부"),
        ),
        migrations.AddField(
            model_name="hintrequest",
            name="problem_str_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="문제 ID (문자열)"
            ),
        ),
        migrations.AlterField(
            model_name="aimodelconfig",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="HuggingFace API 방식 사용 시 필요",
                max_length=200,
                verbose_name="Hugging Face API Key",
            ),
        ),
        migrations.AlterField(
            model_name="aimodelconfig",
            name="mode",
            field=models.CharField(
                choices=[
                    ("api", "API 방식 (Hugging Face)"),
                    ("openai", "OpenAI API"),
                    ("local", "로컬 로드 방식"),
                    ("runpod", "Runpod vLLM 방식"),
                ],
                default="api",
                max_length=20,
                verbose_name="모델 사용 방식",
            ),
        ),
        migrations.AlterField(
            model_name="aimodelconfig",
            name="model_name",
            field=models.CharField(
                choices=[
                    (
                        "meta-llama/Llama-3.2-3B-Instruct",
                        "Llama 3.2 3B Instruct (API 모드 지원)",
                    ),
                    (
                        "Qwen/Qwen2.5-Coder-32B-Instruct",
                        "Qwen 2.5 Coder 32B (API 모드 지원)",
                    ),
                    (
                        "mistralai/Mistral-7B-Instruct-v0.3",
                        "Mistral 7B Instruct (API 모드 지원)",
                    ),
                    ("google/gemma-2-9b-it", "Gemma 2 9B IT (API 모드 지원)"),
                    (
                        "ModelCloud/Brumby-14B-Base-GPTQMODEL-W4A16-v2",
                        "Brumby 14B Base (API 모드 지원)",
                    ),
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo (OpenAI)"),
                    ("gpt-4", "GPT-4 (OpenAI)"),
                    ("gpt-4o", "GPT-4o (OpenAI)"),
                ],
                default="meta-llama/Llama-3.2-3B-Instruct",
                max_length=200,
                verbose_name="모델 이름",
            ),
        ),
        migrations.AlterField(
            model_name="hintrequest",
            name="hint_level",
            field=models.CharField(
                blank=True,
                choices=[("small", "소 힌트"), ("medium", "중 힌트"), ("large", "대 힌트")],
                max_length=20,
                verbose_name="힌트 레벨",
            ),
        ),
        migrations.AlterField(
            model_name="hintrequest",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hint_requests",
                to="coding_test.problem",
            ),
        ),
    ]
