# Generated by Django 5.0.1 on 2025-12-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coding_test", "0018_add_hint_evaluation_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="hintrequest",
            name="code_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="코드 해시"
            ),
        ),
        migrations.AddField(
            model_name="hintrequest",
            name="coh_depth",
            field=models.IntegerField(default=0, verbose_name="COH 깊이"),
        ),
        migrations.AddField(
            model_name="hintrequest",
            name="hint_branch",
            field=models.CharField(blank=True, max_length=10, verbose_name="힌트 분기"),
        ),
    ]
